version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
hooks:
  AfterInstall:
    - location: codedeploy-scripts/prepare.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: codedeploy-scripts/link.sh
      timeout: 300
      runas: root
